apiVersion: apps/v1
kind: Deployment
metadata:
  name: DjangoAk
  labels:
    app: DjangoAk
    kubernetes.azure.com/generator: devhub
  namespace: django-aks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DjangoAk
  template:
    metadata:
      labels:
        app: DjangoAk
    spec:
      containers:
        - name: DjangoAk
          image: acrworkflow1728972648800.azurecr.io/image-workflow-1728972648800:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
