apiVersion: v1
kind: Service
metadata:
  name: DjangoAk
  namespace: namespace-workflow-1728972139038
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: DjangoAk
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000